- hosts: all
  become: yes
  tasks:
    - name: Install prerequisites for docker
      apt:
        name:
          - libffi-dev
          - libssl-dev
          - python3
          - python3-pip
        update_cache: yes
        state: present
    - name: Remove python-configparser package
      apt:
        name: python-configparser
        state: absent
    - name: get docker convenience script
      shell: curl -fsSL https://get.docker.com -o get-docker.sh
      args:
        creates: /home/{{ piuser }}/get-docker.sh
    - name: install docker
      shell: sh /home/{{ piuser }}/get-docker.sh
      args:
        creates: /usr/bin/docker
    - name: make pi user execute docker commands
      shell: usermod -aG docker {{ piuser }}
    - name: Install docker compose
      apt:
        name:
          - docker-compose-plugin
        update_cache: yes
        state: present
