# To be invoked with `ansible-playbook main.yml`

- name: Set up OpenHAB on Raspberry OS (Bullseye)
  hosts: openhabs
  become: true
  tasks:
    - include_role: 
        name: roles/docker
#    - name: reboot host
#      reboot:
    - include_role: 
        name: roles/openhab
      vars:
        system_user: "{{ piuser }}"