# To be invoked with `ansible-playbook main.yml`

- name: Set up OpenHAB on Raspberry OS (Bullseye)
  hosts: all
  become: true
  tasks:
    - include_role:
        name: roles/init-rpi
    - include_role:
        name: roles/docker
    - include_role:
        name: roles/openhab
      vars:
        system_user: "{{ piuser }}"
        openhab_version: 4.2.0
    - include_role:
        name: roles/frontail
